#!/bin/bash

# Function to make commands less annoying
hc() {
    herbstclient "$@"
}

# monitor bs
autorandr -c

hc detect_monitors

# compton
if ! pgrep picom; then
    picom -b
fi


#polybar
~/.config/herbstluftwm/bin/polybar/bar 

hc emit_hook reload

xsetroot -solid '#2e3440'
~/.fehbg

#polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# hc set tree_style '╾│ ├└╼─┐'
hc set tree_style '╾│ ├╰╼─╮'

# unlock, just to be sure
hc unlock